# Generated by Django 5.1.2 on 2024-10-09 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=300)),
                ('medical_history', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('reason_for_visit', models.TextField()),
                ('patient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hms.patient')),
            ],
        ),
    ]
